name: Continuous Integration

on:
  push:
    branches: 
      - master
      - release/*
      - ci
  pull_request:
    branches: 
      - master
      - release/*
    
jobs:
  frontend:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    
    - name: Create network
      run:  docker network create api-backend
    
    - name: Build environment
      run: docker-compose up -d --build
